### ISSUE TITLE
Build materials and keymaps

### ISSUE THREAD

**Issue by nulani38728** [nickcoutsos/dactyl-deskmount#2]
Kudos on the ingenuity of this project, it's a superb idea. I really like the caseless, multi-pronged mounting bracket and the custom arm mount.

1. Do you have any recommended materials for the different printed components?
2. I was going to use the default firmware provided under `handwired/dacyl` in the qmk  repo and just add a custom keymap on top of that. Did you make any modifications to the firmware itself, or just the keymap? If so, can you share it?

Thanks!

**Comment by nickcoutsos** [comment]
Hey, thanks for your interest!

All printed pieces were done in Prusament PLA. I don't know if PETG might helped with rigidity, though.

A while back I replaced the bottom mount with a version that's slightly thicker and extends to the screw mounts on the outer columns to prevent the plate from flexing too much, and since then I replaced the whole ball mount with static hooks (I think I still need to upload this). This gives me the most stability at the cost of any chance to play with different angles on the fly, which, trying to make adjustments with the ball mount just became tedious.

I used a custom firmware based on the split_common, but I think you should be able to use one of the existing dactyl implementations as long as you wire things correctly. My firmware wasn't anything special, aside from being specific to this 6x3+3 physical layout, but I did include a custom patch to make RGB matrix animations sync across both sides of the keyboard.

Ultimately, I've been using the keyboard for about a year now and aside from the changes I've described I'm also planning on switching to a more typical desk-top keyboard with the same layout.

* I find myself hating the low profile switches, at least for a contoured keyboard, and would switch back to my [dactyl-flatpacked](https://github.com/nickcoutsos/dactyl-flatpacked/) if I were less concerned about bulkiness
* Having slightly more desk space is nice, but having the keyboard sticking out makes it awkward to reach across my desk
* I think I don't care much about playing around with keyboard tilt and tenting, but not having a way to effortlessly move the keyboard halves around (and angle my wrists inward as appropriate) is too limiting.

That said let me know if you have any more questions, I'm happy to talk more about things!

**Comment by nulani38728** [comment]
Thanks for the reply!

If you're considering going back to a desktop keyboard in this configuration, I'd recommend the Kinesis Advantage 2. If the height is an issue, a height adjustable desk is crucial here. I personally find having a second, smaller, and adjustable desk (essentially a giant keyboard tray) underneath the main desk to be a good solution if your upper desk is a fixed height.

There are a number of modifications you could make to this keyboard to enhance the experience -- can share some of those if you are interested.

I'm coming from using the KA2 as my main input device, but have developed RSI in the elbow from having the joint constantly bent. So for me, different tenting/tilting mechanisms are very attractive; I was thinking of using just the top part of your design on my existing tripod mount setup.

What I have rigged up now is Manfrotto clamps with articulating arms. This gives you a huge, 360 degree range of motion and enables configurations like standing and typing with arms at sides, sitting with different tilts, keyboards at sides of chair, etc. It's a bit ungainly and definitely adds a big contraption to your desk, but it's rock solid, and the arms are among the thinnest you can find. The 1/4 screw mount also lets me swap in microphones, cameras, or other accessories on the fly onto the arms. 

You do have to fiddle with the knobs each time, but this is a necessary evil for the gains you get. You could also use a cold shoe/magnet mount to facilitate swapping input devices in and out, too.

I didn't have anything else like the Kinesis on hand, so I put a non-contoured split keyboard in a square matrix on the arms for now, but I'm finding it extremely difficult to use due to the lack of thumb clusters and key layout, which led to this saga to find something in a similar shape (Dactyl). 

Thanks for the tip about the low profile switches. I was kind of intrigued by the Choc switches, since there is a 12g spring available, and that would be pretty nice for reducing strain, but the chiclet-style keycaps seem unpleasant (alien?) to use. I'll probably just stick to Gateron Clears if the low profile is not so good. I guess you never know until you try.

If you're planning to shelve this keyboard and go back to a desktop one, I'd be interested in buying it from you if it's not going to see any use -- would give me something ready made to experiment with. Just a thought.

Never did a from-scratch handwired build before, so I am approaching this with trepidation but enthusiasm.

**Comment by nickcoutsos** [comment]
For what its worth, regarding the choc switches, I've only tried them here so I don't know whether it's the spring weight or the contours that makes me dislike them. I know others have built dactyls with choc switches. At some point I may try making a flat keyboard like the corne or gergo using these switches.

If you have any soldering experience at all then the only problem with handwiring is all of the wire cutting and stripping, and maybe trying to squeeze things into tight spaces if you try to keep the microcontroller tucked out of the away.

**Comment by nulani38728** [comment]
I went ahead and printed it and have it partially done now, seems to not be too difficult in the end. I went with contoured keys I already had on hand. It was nice that you used a definitions file to make it modular. Thanks for the nice design!

**Comment by nickcoutsos** [comment]
Awesome! I'd love to see pictures when you're ready :)
